#!/bin/sh

# confから変数を読みこむ
. .conf

# hubot-twitter-mention用の環境変数
export HUBOT_TWITTER_CONSUMER_KEY=$HUBOT_TWITTER_CONSUMER_KEY
export HUBOT_TWITTER_CONSUMER_SECRET=$HUBOT_TWITTER_CONSUMER_SECRET
export HUBOT_TWITTER_ACCESS_TOKEN_KEY=$HUBOT_TWITTER_ACCESS_TOKEN_KEY
export HUBOT_TWITTER_ACCESS_TOKEN_SECRET=$HUBOT_TWITTER_ACCESS_TOKEN_SECRET
export HUBOT_TWITTER_MENTION_QUERY=$HUBOT_TWITTER_MENTION_QUERY
export HUBOT_TWITTER_MENTION_ROOM=$HUBOT_TWITTER_MENTION_ROOM

# hubot-slack用の環境変数
export HUBOT_SLACK_TOKEN=$HUBOT_SLACK_TOKEN

# hubotの起動コマンドでアダプタの指定をslackにする
bin/hubot -a slack
